### ISSUE TITLE
check condition failure on input '["'

### ISSUE THREAD

**Issue by fridis** [fridis/fuzion#107]
This two characters cause a crash:
```
 > echo "[\"" | ./build/bin/fz -

-:1:3: error 1: Unexpected control sequence in constant string.
["
--^
Found unexpected control sequence 'LF ' (0xa) in constant string starting at -:1:2:
["
-^


-:1:4: error 2: Syntax error: expected term (lbrace, lparen, lcrochet, fun, string, integer, old, match, or name), found end-of-file
["
---^
While parsing: term, parse stack: term, opTail, opExpr, expr, initArray, bracketTerm, exprInLine, stmnt, stmnts, stmntsEof


-:1:1: error 3: Constructor code should result in type 'unit'
["
^
Type returned by this constructor's implementation is 'array<**error**>'
To solve this, you could turn this contstructor into routine by adding a matching result type compatible to 'array<**error**>' or by using '=>' instead of 'is' to infer the result type from the result expression.
Alternatively, you could explicitly return 'unit' as the last statement or explicitly ignore the result of the last expression by an assignment '_ := <expression>'.

java.lang.Error: check-condition1 failed!
	at dev.flang.util.ANY.check(ANY.java:387)
	at dev.flang.ir.Clazz.clazzForField(Clazz.java:899)
	at dev.flang.ir.Clazz.layout(Clazz.java:693)
	at dev.flang.ir.Clazz.layout(Clazz.java:699)
	at dev.flang.ir.Clazz.layoutAndHandleCycle(Clazz.java:648)
	at dev.flang.ir.Clazzes.findAllClasses(Clazzes.java:402)
	at dev.flang.be.interpreter.Interpreter.<init>(Interpreter.java:155)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:482)
	at dev.flang.tools.Tool.run(Tool.java:166)
	at dev.flang.tools.Fuzion.main(Fuzion.java:209)

```

**Comment by fridis** [comment]
fixed by 9f1c332a2c4cbbbe60f3ef6eccf59b3f1d129604
