### ISSUE TITLE
match over type parameter causes front end crash

### ISSUE THREAD

**Issue by fridis** [fridis/fuzion#11]
```
 > cat testMatch.fz
testMatch is
  x<A: Option<string>>(a A) is
    match a
      string => say "string"
      nil => say "nil"

  x<Option<string>> "bla"
 > ./build/bin/fz testMatch
java.lang.Error: check-condition failed!
	at dev.flang.util.ANY.check(ANY.java:371)
	at dev.flang.ast.Type.featureOfType(Type.java:1074)
	at dev.flang.ast.Match.resolveTypes(Match.java:146)
	at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1263)
	at dev.flang.ast.Match.visit(Match.java:127)
	at dev.flang.ast.Match.visit(Match.java:48)
	at dev.flang.ast.Block.visit(Block.java:186)
	at dev.flang.ast.Block.visit(Block.java:41)
	at dev.flang.ast.Impl.visit(Impl.java:314)
	at dev.flang.ast.Feature.visit(Feature.java:1011)
	at dev.flang.ast.Feature.resolveTypes(Feature.java:1305)
	at dev.flang.ast.Feature.resultTypeIfPresent(Feature.java:3183)
	at dev.flang.ast.Call.resolveTypes(Call.java:1300)
	at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1258)
	at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1250)
	at dev.flang.ast.Call.visit(Call.java:836)
	at dev.flang.ast.Call.visit(Call.java:47)
	at dev.flang.ast.Block.visit(Block.java:186)
	at dev.flang.ast.Block.visit(Block.java:41)
	at dev.flang.ast.Impl.visit(Impl.java:314)
	at dev.flang.ast.Feature.visit(Feature.java:1011)
	at dev.flang.ast.Feature.resolveTypes(Feature.java:1305)
	at dev.flang.ast.Resolution.resolveOne(Resolution.java:412)
	at dev.flang.ast.Resolution.resolve(Resolution.java:378)
	at dev.flang.ast.Resolution.<init>(Resolution.java:216)
	at dev.flang.fe.FrontEnd.createMIR(FrontEnd.java:127)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$2(Fuzion.java:537)
	at dev.flang.tools.Fuzion.<init>(Fuzion.java:236)
	at dev.flang.tools.Fuzion.main(Fuzion.java:219)
```

**Comment by fridis** [comment]
closed by [this commit](https://github.com/fridis/fuzion/commit/39fb85d5c14a0e6fd0d3cde74e749ad2f8421f90)
