### ISSUE TITLE
Small example provokes check condition to fail during Call type resultion.

### ISSUE THREAD

**Issue by fridis** [fridis/fuzion#12]
```
 > cat testCrash.fz
testCrash is

  next =>
    if 1 > 0
      res := 1
    else if 1 > 0
      res := 1
    else
      res =  1
 > ./build/bin/fz testCrash
java.lang.Error: check-condition failed!
	at dev.flang.util.ANY.check(ANY.java:371)
	at dev.flang.ast.Call.loadCalledFeature(Call.java:680)
	at dev.flang.ast.Call.resolveTypes(Call.java:1279)
	at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1258)
	at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1250)
	at dev.flang.ast.Call.visit(Call.java:837)
	at dev.flang.ast.Call.visit(Call.java:835)
	at dev.flang.ast.Call.visit(Call.java:47)
	at dev.flang.ast.Block.visit(Block.java:186)
	at dev.flang.ast.If.visit(If.java:288)
	at dev.flang.ast.If.visit(If.java:292)
	at dev.flang.ast.If.visit(If.java:41)
	at dev.flang.ast.Block.visit(Block.java:186)
	at dev.flang.ast.Block.visit(Block.java:41)
	at dev.flang.ast.Impl.visit(Impl.java:314)
	at dev.flang.ast.Feature.visit(Feature.java:1011)
	at dev.flang.ast.Feature.resolveTypes(Feature.java:1305)
	at dev.flang.ast.Resolution.resolveOne(Resolution.java:412)
	at dev.flang.ast.Resolution.resolve(Resolution.java:378)
	at dev.flang.ast.Resolution.<init>(Resolution.java:216)
	at dev.flang.fe.FrontEnd.createMIR(FrontEnd.java:127)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$2(Fuzion.java:537)
	at dev.flang.tools.Fuzion.<init>(Fuzion.java:236)
	at dev.flang.tools.Fuzion.main(Fuzion.java:219)
```

**Comment by fridis** [comment]
This is a duplicate of #50 and was also fixed by 3232a5447309028cda2f9f1e4e76b05e02f95488.
