### ISSUE TITLE
lambda return string.asString on a non-ref heir of string results in interpreter crash

### ISSUE THREAD

**Issue by fridis** [fridis/fuzion#13]
Likely reason for this is that boxing is missing when string.asString is called or returns. 
```
 > cat testAsString.fz
testAsString is

  myString : string is
  f Function<string, myString> := fun (m myString) => m.asString
  say f myString
 > ./build/bin/fz testAsString

error 1: *** java.lang.ClassCastException: class dev.flang.be.interpreter.LValue cannot be cast to class dev.flang.be.interpreter.Instance (dev.flang.be.interpreter.LValue and dev.flang.be.interpreter.Instance are in unnamed module of loader 'app')
Call stack:
fuzion.std.out.println: /home/fridi/fuzion/work/build/lib/fuzion/std/out.fz:34:16:
    for c in s.asString.asBytes do
---------------^
say: /home/fridi/fuzion/work/build/lib/say.fz:29:29:
say(s ref Object) => stdout.println(s)
----------------------------^
testAsString: ./testAsString.fz:5:3:
  say f myString
--^


java.lang.ClassCastException: class dev.flang.be.interpreter.LValue cannot be cast to class dev.flang.be.interpreter.Instance (dev.flang.be.interpreter.LValue and dev.flang.be.interpreter.Instance are in unnamed module of loader 'app')
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:224)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:556)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:215)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:556)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:215)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:239)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:269)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:269)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:269)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:837)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$7(Interpreter.java:737)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:227)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:269)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:837)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$7(Interpreter.java:737)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:227)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:269)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:837)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$7(Interpreter.java:737)
	at dev.flang.be.interpreter.Interpreter.run(Interpreter.java:178)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$2(Fuzion.java:547)
	at dev.flang.tools.Fuzion.<init>(Fuzion.java:236)
	at dev.flang.tools.Fuzion.main(Fuzion.java:219)
```

**Comment by fridis** [comment]
This is fixed by now, but it requires myString to redefine utf8
