### ISSUE TITLE
interpreter produces 'Cannot create LValue' when converting u64-expression to string

### ISSUE THREAD

**Issue by fridis** [fridis/fuzion#17]
```
 > cat testU64inString.fz 
testU64inString is
  "" + (1.as_u64&1)
 > ./build/bin/fz testU64inString.fz 

error 1: *** java.lang.Error: Cannot create LValue from class dev.flang.be.interpreter.u64Value
Call stack:


java.lang.Error: Cannot create LValue from class dev.flang.be.interpreter.u64Value
	at dev.flang.be.interpreter.Value.at(Value.java:157)
	at dev.flang.be.interpreter.Interpreter.fieldSlot(Interpreter.java:1066)
	at dev.flang.be.interpreter.Interpreter.getField(Interpreter.java:1140)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:421)
	at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:554)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:215)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:269)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:830)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$7(Interpreter.java:730)
	at dev.flang.be.interpreter.Interpreter.run(Interpreter.java:178)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$2(Fuzion.java:547)
	at dev.flang.tools.Fuzion.<init>(Fuzion.java:236)
	at dev.flang.tools.Fuzion.main(Fuzion.java:219)
```

**Comment by fridis** [comment]
This problem has been fixed meanwhile.
