### ISSUE TITLE
check failure when accessing one of several fields early

### ISSUE THREAD

**Issue by fridis** [fridis/fuzion#18]
```
 > cat testVars.fz 
testVars is
  b := 1 + b
  b := 1 + b
 > ./build/bin/fz testVars
  b := 1 + b
-----------^
java.lang.Error: check-condition failed!
	at dev.flang.util.ANY.check(ANY.java:371)
	at dev.flang.ast.Call.loadCalledFeature(Call.java:680)
	at dev.flang.ast.Call.resolveTypes(Call.java:1279)
	at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1258)
	at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1250)
	at dev.flang.ast.Call.visit(Call.java:837)
	at dev.flang.ast.Call.lambda$visit$0(Call.java:829)
	at dev.flang.ast.Feature.resolveTypes(Feature.java:1323)
	at dev.flang.ast.Resolution.resolveOne(Resolution.java:412)
	at dev.flang.ast.Resolution.resolve(Resolution.java:378)
	at dev.flang.ast.Resolution.<init>(Resolution.java:216)
	at dev.flang.fe.FrontEnd.createMIR(FrontEnd.java:127)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$2(Fuzion.java:537)
	at dev.flang.tools.Fuzion.<init>(Fuzion.java:236)
	at dev.flang.tools.Fuzion.main(Fuzion.java:219)
 > 
```

**Comment by fridis** [comment]
This is also fixed by 3232a5447309028cda2f9f1e4e76b05e02f95488, a duplicate of #50.
