### ISSUE TITLE
Check failure in small example using asList

### ISSUE THREAD

**Issue by fridis** [fridis/fuzion#26]
This example

```
 > cat checkFailure.fzfz 
checkFailure is

 m.keys.asList
 m.items2

 m is
  items2 List<tuple<i32, unit>> is
    res : List<tuple<i32,unit>> is
         redef asStream => do
    res
  items List<tuple<i32,unit>> is abstract
  keys List<i32> is do
```
causes `fz` to crash

```
 > cat checkFailure.fzfz | ./build/bin/fz -
java.lang.Error: check-condition failed!
	at dev.flang.util.ANY.check(ANY.java:371)
	at dev.flang.ir.Clazz.findRedefinition(Clazz.java:686)
	at dev.flang.ir.Clazz.lookup(Clazz.java:760)
	at dev.flang.ir.Clazzes.findClazzes(Clazzes.java:689)
	at dev.flang.ir.Clazz$FindClassesVisitor.action(Clazz.java:987)
	at dev.flang.ir.Clazz$FindClassesVisitor.action(Clazz.java:981)
	at dev.flang.ast.Call.visit(Call.java:915)
	at dev.flang.ast.Call.visit(Call.java:47)
	at dev.flang.ast.Block.visit(Block.java:214)
	at dev.flang.ast.Block.visit(Block.java:41)
	at dev.flang.ast.Assign.visit(Assign.java:217)
	at dev.flang.ast.Assign.visit(Assign.java:39)
	at dev.flang.ast.Block.visit(Block.java:214)
	at dev.flang.ast.Block.visit(Block.java:41)
	at dev.flang.ast.Impl.visit(Impl.java:314)
	at dev.flang.ast.Feature.visit(Feature.java:1009)
	at dev.flang.ir.Clazz$FindClassesVisitor.visitAncestors(Clazz.java:994)
	at dev.flang.ir.Clazz.findAllClassesWhenCalled(Clazz.java:1045)
	at dev.flang.ir.Clazzes.findAllClasses(Clazzes.java:384)
	at dev.flang.be.interpreter.Interpreter.<init>(Interpreter.java:156)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$2(Fuzion.java:576)
	at dev.flang.tools.Fuzion.<init>(Fuzion.java:240)
	at dev.flang.tools.Fuzion.main(Fuzion.java:223)
```

**Comment by fridis** [comment]
Problem understood: Redefining a feature with `void` result is not fully supported by IR. Here is a better example
```
redefineAsVoid is

 p is
  f string is abstract
  say f+"!"

 h : p is

  # void is assignment compatible to anything, so we can redefine f
  # to return void!
  #
  redef f void is
    say "I give up:"
    fuzion.std.exit 0

 h
```
