### ISSUE TITLE
C backend crash due to call to clazz that does not need code according to FUIR

### ISSUE THREAD

**Issue by fridis** [fridis/fuzion#27]
Using the example
```
cbackendCallsNoCodeClazz is

 psSet2<string>.asString

 psSet2<K : ordered<K>> : Set<K>, List<K> is
  psm := psMap2<K,unit>
  redef asList => psm.keys.asList

 psMap2<K : ordered<K>, V> : map<K, V> is
  index [] (k K) option<V> is do
  asKeyArray array<K> is do
  redef items List<tuple<K,V>> is
    res : List<tuple<K,V>> is
      redef asStream =>
        asKeyArray.map<tuple<K,V>>(fun (k K) => (k, psMap2.this[k].unwrap)).asStream
    res
```
results in a precondition failure in the C backend due to a call to ` ref stream<tuple<string, unit>>.map<string>` while, `!_fuir.clazzNeedsCode(cc)` for this clazz:
```
 > PRECONDITIONS=true ./build/bin/fz -c cbackendCallsNoCodeClazz
clazzNeedsCode2: ref stream<tuple<string, unit>>.map<string> is  not instantiated  && true
Called ref stream<tuple<string, unit>>.map<string> on ref stream<tuple<string, unit>> but does not need code!
while compiling cbackendCallsNoCodeClazz.psMap2<string, unit>.keys.ref res.asStream
java.lang.Error: require-condition1 failed!
	at dev.flang.util.ANY.require(ANY.java:66)
	at dev.flang.be.c.C.call(C.java:652)
	at dev.flang.be.c.C.createCode(C.java:450)
	at dev.flang.be.c.C.createCode(C.java:292)
	at dev.flang.be.c.C.codeForRoutine(C.java:899)
	at dev.flang.be.c.C.code(C.java:837)
	at dev.flang.be.c.C$CompilePhase$4.compile(C.java:67)
	at dev.flang.be.c.C.lambda$createCode$0(C.java:207)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEachOrdered(ReferencePipeline.java:772)
	at dev.flang.be.c.C.createCode(C.java:203)
	at dev.flang.be.c.C.compile(C.java:152)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$2(Fuzion.java:580)
	at dev.flang.tools.Fuzion.<init>(Fuzion.java:240)
	at dev.flang.tools.Fuzion.main(Fuzion.java:223)
```

**Comment by fridis** [comment]
Problem understood, here is a simpler example
```
cbackendCallsNoCodeClazz3 is

  # x is declared to return y, but performs an endless loop
  #
  x y is do

  # y is only used as a type, never instantiated
  #
  y is

    # y.z is never called and not compiled!
    #
    z is say "z!"

  # y0 will never be set since x will not return
  y0 := x;

  # so this call is dead code
  y0.z
```
The code after the call to `x` cannot be reached, but the compiler does not really know this.
