### ISSUE TITLE
java.lang.Error: check-condition failed!

### ISSUE THREAD

**Issue by michaellilltokiwa** [fridis/fuzion#52]
might be similar to #50 
```
# http://rosettacode.org/wiki/Faulhaber's_formula
faulhaber_example is
  bernoulli (n i32) fraction<i32>
    pre
      n >= 0
  is
    a := array<fraction<i32>> n+1, fun (i i32) => 1 ⁄ 1
    for m in 0..n do
      set a := a.put m , (1  ⁄  (m + 1))
      for k in m..1 : -1 do
        set a := a.put (k - 1), ((a[k - 1] - a[k]) * (k ⁄ 1))
    if n != 1
      a[0]
    else
      -a[0]
//====
  binomial(n, k i32)
    pre
      n > 0, k >= 0
    => factorial(n) / (factorial(k) * factorial(n-k))
//====
  factorial(x i32)
    pre
      x >= 0
    =>
    res i32 := 1
    for
      i i32 := 1, i+1
    while i<=x
      set res := res * i;
    res
//====
  faulhaber(p i32) =>
    res := "$p : "
    q := 1  ⁄  (p+1)
    sign := -1⁄1
    for j in 0..p do
      set sign := sign * (-1⁄1)
      b := binomial(p+1, j)  ⁄  1
      coeff := q * (sign / (1⁄1)) * b * bernoulli(j)
      if coeff != (0⁄1)
        if j = 0
          if coeff = (1⁄1)
          else
            if coeff = (-1⁄1)
              res := res + "-"
            else
              res := res + "$coeff"
          else
            if coeff = (1⁄1)
              " + "
            else
              if coeff = (-1⁄1)
                res := res + " - "
              else
                if coeff > (0⁄1)
                  res := res + " + $coeff"
                else
                  minusCoeff := -coeff
                  res := res + " - $minusCoeff"
        pwr := p + 1 - j
        if pwr > 1
          res := res + "n^$pwr"
        else
          res := res + "n"
    res
//====
  for i in 0..11 do
    say(faulhaber(i))


```
        java.lang.Error: check-condition failed!
        at dev.flang.util.ANY.check(ANY.java:371)
        at dev.flang.ast.Call.loadCalledFeature(Call.java:749)
        at dev.flang.ast.Call.resolveTypes(Call.java:1357)
        at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1277)
        at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1269)
        at dev.flang.ast.Call.visit(Call.java:915)
        at dev.flang.ast.Call.visit(Call.java:913)
        at dev.flang.ast.Feature.visit(Feature.java:2539)
        at dev.flang.ast.Block.visit(Block.java:214)
        at dev.flang.ast.If.visit(If.java:293)
        at dev.flang.ast.If.visit(If.java:300)
        at dev.flang.ast.If.visit(If.java:41)
        at dev.flang.ast.Block.visit(Block.java:214)
        at dev.flang.ast.If.visit(If.java:293)
        at dev.flang.ast.If.visit(If.java:41)
        at dev.flang.ast.Block.visit(Block.java:214)
        at dev.flang.ast.If.visit(If.java:293)
        at dev.flang.ast.If.visit(If.java:41)
        at dev.flang.ast.Block.visit(Block.java:214)
        at dev.flang.ast.Block.visit(Block.java:41)
        at dev.flang.ast.Impl.visit(Impl.java:315)
        at dev.flang.ast.Feature.visit(Feature.java:1030)
        at dev.flang.ast.Feature.resolveTypes(Feature.java:1324)
        at dev.flang.ast.Feature.resultTypeIfPresent(Feature.java:3208)
        at dev.flang.ast.Call.resolveTypes(Call.java:1379)
        at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1277)
        at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1269)
        at dev.flang.ast.Call.visit(Call.java:915)
        at dev.flang.ast.Call.visit(Call.java:47)
        at dev.flang.ast.Block.visit(Block.java:214)
        at dev.flang.ast.If.visit(If.java:293)
        at dev.flang.ast.If.visit(If.java:41)
        at dev.flang.ast.Block.visit(Block.java:214)
        at dev.flang.ast.Block.visit(Block.java:41)
        at dev.flang.ast.Block.visit(Block.java:214)
        at dev.flang.ast.Block.visit(Block.java:41)
        at dev.flang.ast.Impl.visit(Impl.java:315)
        at dev.flang.ast.Feature.visit(Feature.java:1030)
        at dev.flang.ast.Feature.resolveTypes(Feature.java:1324)
        at dev.flang.ast.Feature.resultTypeIfPresent(Feature.java:3208)
        at dev.flang.ast.Call.resolveTypes(Call.java:1379)
        at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1277)
        at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1269)
        at dev.flang.ast.Call.visit(Call.java:915)
        at dev.flang.ast.Call.lambda$visit$0(Call.java:907)
        at dev.flang.ast.Feature.resolveTypes(Feature.java:1342)
        at dev.flang.ast.Feature.resultTypeIfPresent(Feature.java:3208)
        at dev.flang.ast.Call.resolveTypes(Call.java:1379)
        at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1277)
        at dev.flang.ast.Feature$ResolveTypes.action(Feature.java:1269)
        at dev.flang.ast.Call.visit(Call.java:915)
        at dev.flang.ast.Call.visit(Call.java:47)
        at dev.flang.ast.Block.visit(Block.java:214)
        at dev.flang.ast.If.visit(If.java:293)
        at dev.flang.ast.If.visit(If.java:41)
        at dev.flang.ast.Block.visit(Block.java:214)
        at dev.flang.ast.Block.visit(Block.java:41)
        at dev.flang.ast.Block.visit(Block.java:214)
        at dev.flang.ast.Block.visit(Block.java:41)
        at dev.flang.ast.Impl.visit(Impl.java:315)
        at dev.flang.ast.Feature.visit(Feature.java:1030)
        at dev.flang.ast.Feature.resolveTypes(Feature.java:1324)
        at dev.flang.ast.Resolution.resolveOne(Resolution.java:411)
        at dev.flang.ast.Resolution.resolve(Resolution.java:378)
        at dev.flang.ast.Resolution.<init>(Resolution.java:216)
        at dev.flang.fe.FrontEnd.createMIR(FrontEnd.java:142)
        at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:471)
        at dev.flang.tools.Tool.run(Tool.java:163)
        at dev.flang.tools.Fuzion.main(Fuzion.java:209)

**Comment by fridis** [comment]
Here is a smaller example that provokes this bug: 
```
f is
  do
    if true
      r := r
    else
      r := ""
```
The problem is feature lookup for `r` that is declared twice, even though both declarations should be invisible at this point.
