### ISSUE TITLE
java.lang.ClassCastException: class [B cannot be cast to class [I ([B and [I are in module java.base of loader 'bootstrap')

### ISSUE THREAD

**Issue by michaellilltokiwa** [fridis/fuzion#53]
```
# http://rosettacode.org/wiki/Faulhaber's_formula
faulhaber_example is
  bernoulli (n i32) fraction<i32>
    pre
      n >= 0
  is
    a := array<fraction<i32>> n+1, fun (i i32) => 1 ⁄ 1
    for m in 0..n do
      set a := a.put m , (1  ⁄  (m + 1))
      for k in m..1 : -1 do
        set a := a.put (k - 1), ((a[k - 1] - a[k]) * (k ⁄ 1))
    if n != 1
      a[0]
    else
      -a[0]
//====
  binomial(n, k i32)
    pre
      n > 0, k >= 0
    => factorial(n) / (factorial(k) * factorial(n-k))
//====
  factorial(x i32)
    pre
      x >= 0
    =>
    res i32 := 1
    for
      i i32 := 1, i+1
    while i<=x
      set res:= res * i;
    res
//====
  faulhaber(p i32) =>
    res:= "$p : "
    q := 1  ⁄  (p+1)
    sign := -1⁄1
    for j in 0..p do
      set sign := sign * (-1⁄1)
      b := binomial(p+1, j)  ⁄  1
      coeff := q * (sign / (1⁄1)) * b * bernoulli(j)
      if coeff != (0⁄1)
        if j = 0
          if coeff = (1⁄1)
          else
            if coeff = (-1⁄1)
              set res:= res + "-"
            else
              set res:= res + "$coeff"
          else
            if coeff = (1⁄1)
              " + "
            else
              if coeff = (-1⁄1)
                set res:= res + " - "
              else
                if coeff > (0⁄1)
                  set res:= res + " + $coeff"
                else
                  minusCoeff := -coeff
                  set res:= res + " - $minusCoeff"
        pwr := p + 1 - j
        if pwr > 1
          set res:= res + "n^$pwr"
        else
          set res:= res + "n"
    res
//====
  for i in 0..11 do
    say(faulhaber(i))

```
```
error 1: *** java.lang.ClassCastException: class [B cannot be cast to class [I ([B and [I are in module java.base of loader 'bootstrap')
Call stack:
sys.array<i32>.index [ ]: /home/not_synced/fuzion/build/lib/sys/array.fz:46:5:
    get<T> data, i
----^
ref conststring.index [ ]: /home/not_synced/fuzion/build/lib/array.fz:40:18:
    internalArray[i]
-----------------^
ref array<i32>.ref asStream.next: /home/not_synced/fuzion/build/lib/array.fz:80:45:
    redef next => set x := x + 1; array_this[x-1]
--------------------------------------------^
strings.zeroChar: /home/not_synced/fuzion/build/lib/strings.fz:99:34:
  zeroChar  => "0".utf8.asStream.next
---------------------------------^
ref i32.asString.ref #anonymous0.ref utf8.asStream.ref #anonymous0.next: /home/not_synced/fuzion/build/lib/integer.fz:144:46:
                    r := if (d < 10) strings.zeroChar + d else strings.aChar + d -  10
---------------------------------------------^
strings.ref fromArray.ref utf8.ref asStream.next: /home/not_synced/fuzion/build/lib/strings.fz:84:60:
        redef next    => findNext; set gotNext := false; s.next
-----------------------------------------------------------^
fuzion.std.out.println: /home/not_synced/fuzion/build/lib/fuzion/std/out.fz:34:9:
    for c in s.asString.utf8 do
--------^
say: /home/not_synced/fuzion/build/lib/say.fz:29:29:
say(s ref Object) => stdout.println(s)
----------------------------^
faulhaber_example.#loop4: /home/not_synced/flang_dev/content/examples/examples/faulhaber.fz:69:5:
    say(faulhaber(i))
----^
faulhaber_example: /home/not_synced/flang_dev/content/examples/examples/faulhaber.fz:68:3:
  for i in 0..11 do
--^


java.lang.ClassCastException: class [B cannot be cast to class [I ([B and [I are in module java.base of loader 'bootstrap')
        at dev.flang.be.interpreter.Intrinsics.sysArrayGet(Intrinsics.java:635)
        at dev.flang.be.interpreter.Intrinsics.lambda$call$16(Intrinsics.java:370)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:253)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:295)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:264)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:295)
        at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:810)
        at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:710)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:253)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:295)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:264)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:295)
        at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:810)
        at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:710)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:253)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:295)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:264)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:295)
        at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:810)
        at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:710)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:253)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:295)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:264)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:295)
        at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:810)
        at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:710)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:253)
        at dev.flang.be.interpreter.Interpreter.executeArgs(Interpreter.java:557)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:241)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:264)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:295)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:304)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:295)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:264)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:295)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:295)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:264)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:295)
        at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:810)
        at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:710)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:253)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:295)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:264)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:295)
        at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:810)
        at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:710)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:253)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:264)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:295)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:295)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:304)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:295)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:295)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:264)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:295)
        at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:810)
        at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:710)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:253)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:295)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:264)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:295)
        at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:810)
        at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:710)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:253)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:295)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:264)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:295)
        at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:810)
        at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:710)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:253)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:295)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:304)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:295)
        at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:295)
        at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:810)
        at dev.flang.be.interpreter.Interpreter.lambda$callable$6(Interpreter.java:710)
        at dev.flang.be.interpreter.Interpreter.run(Interpreter.java:177)
        at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$3(Fuzion.java:484)
        at dev.flang.tools.Tool.run(Tool.java:163)
        at dev.flang.tools.Fuzion.main(Fuzion.java:209)
```

**Comment by fridis** [comment]
This has been fixed meanwhile: 
```
 > ./build/bin/fz faulhaber_example
0 : n
1 : 1⁄2n^2 + 1⁄2n
2 : 1⁄3n^3 + 1⁄2n^2 + 1⁄6n
3 : 1⁄4n^4 + 1⁄2n^3 + 1⁄4n^2
4 : 1⁄5n^5 + 1⁄2n^4 + 1⁄3n^3 - 1⁄30n
5 : 1⁄6n^6 + 1⁄2n^5 + 5⁄12n^4 - 1⁄12n^2
6 : 1⁄7n^7 + 1⁄2n^6 + 1⁄2n^5 - 1⁄6n^3 + 1⁄42n
7 : 1⁄8n^8 + 1⁄2n^7 + 7⁄12n^6 - 7⁄24n^4 + 1⁄12n^2
8 : 1⁄9n^9 + 1⁄2n^8 + 2⁄3n^7 - 7⁄15n^5 + 2⁄9n^3 - 1⁄30n
9 : 1⁄10n^10 + 1⁄2n^9 + 3⁄4n^8 - 7⁄10n^6 + 1⁄2n^4 - 3⁄20n^2
10 : 1⁄11n^11 + 1⁄2n^10 + 5⁄6n^9 - n^7n^5 - 1⁄2n^3 + 5⁄66n
11 : 1⁄12n^12 + 1⁄2n^11 + 11⁄12n^10 - 11⁄8n^8 + 11⁄6n^6 - 11⁄8n^4 + 5⁄12n^2
```
The problem was an inconsistent state of the sources when changing string.utf8 from i32 to u8.
