### ISSUE TITLE
feature declaration as last statement in routine returning Option causes check to fail

### ISSUE THREAD

**Issue by fridis** [fridis/fuzion#6]
Using the following example: 
```
> cat testAssignToChoice.fz
testAssignToChoice is

  x<K,V> is
    y(k K) Option<V> is
      retrieve 23

      retrieve (at i32) Option<V> is
        nil

  v := x<i32, bool>.y 3
```
 
I get this error at runtime:

```
 > ./build/bin/fz testAssignToChoice
error 1: *** java.lang.Error: check-condition failed!
Call stack:
testAssignToChoice: ./testAssignToChoice.fz:10:21:
  v := x<i32, bool>.y 3
--------------------^


java.lang.Error: check-condition failed!
	at dev.flang.util.ANY.check(ANY.java:371)
	at dev.flang.ir.Clazz.getChoiceTag(Clazz.java:1235)
	at dev.flang.be.interpreter.Interpreter.setChoiceField(Interpreter.java:891)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:491)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:239)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:269)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:842)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$7(Interpreter.java:742)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:227)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:239)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:269)
	at dev.flang.be.interpreter.Interpreter.execute(Interpreter.java:269)
	at dev.flang.be.interpreter.Interpreter.callOnInstance(Interpreter.java:842)
	at dev.flang.be.interpreter.Interpreter.lambda$callable$7(Interpreter.java:742)
	at dev.flang.be.interpreter.Interpreter.run(Interpreter.java:178)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$2(Fuzion.java:547)
	at dev.flang.tools.Fuzion.<init>(Fuzion.java:236)
	at dev.flang.tools.Fuzion.main(Fuzion.java:219)
```

Exchanging the declaration and the call to retrieve avoids the problem. Apparently, the declaration of retrieve is replaced by NOP which results in `unit` being returned instead of `nil`.

**Comment by fridis** [comment]
Fixed with commit 42d8a446c881d3b43a476e229d035807cd380634
