### ISSUE TITLE
Small example causes check to fail during Call.checkTypes

### ISSUE THREAD

**Issue by fridis** [fridis/fuzion#9]
Run this code:

```
 > cat checkFailure.fz 
x is
  r := 1.max 1
  if r = 3

x
 > ./build/bin/fz checkFailure.fz
java.lang.Error: check-condition failed!
	at dev.flang.util.ANY.check(ANY.java:371)
	at dev.flang.ast.Call.checkTypes(Call.java:1438)
	at dev.flang.ast.Feature$8.action(Feature.java:2061)
	at dev.flang.ast.Feature$8.action(Feature.java:2059)
	at dev.flang.ast.Call.visit(Call.java:836)
	at dev.flang.ast.Call.visit(Call.java:47)
	at dev.flang.ast.Block.visit(Block.java:186)
	at dev.flang.ast.Block.visit(Block.java:41)
	at dev.flang.ast.Impl.visit(Impl.java:314)
	at dev.flang.ast.Feature.visit(Feature.java:1011)
	at dev.flang.ast.Feature.checkTypes1and2(Feature.java:2059)
	at dev.flang.ast.Resolution.resolveOne(Resolution.java:436)
	at dev.flang.ast.Resolution.resolve(Resolution.java:378)
	at dev.flang.ast.Resolution.<init>(Resolution.java:216)
	at dev.flang.fe.FrontEnd.createMIR(FrontEnd.java:127)
	at dev.flang.tools.Fuzion.lambda$parseArgsForBackend$2(Fuzion.java:537)
	at dev.flang.tools.Fuzion.<init>(Fuzion.java:236)
	at dev.flang.tools.Fuzion.main(Fuzion.java:219)
fridi@yoga:~/fuzion/work 11:16:40 > 

```

**Comment by fridis** [comment]
Here is an even smaller example:
```
 > echo 1.max 1 | ./build/bin/fz -
java.lang.Error: check-condition failed!
	at dev.flang.util.ANY.check(ANY.java:371)
	at dev.flang.ast.Call.checkTypes(Call.java:1438)
	[...]
```
